services:
  - type: web
    name: heart-disease-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn HeartDiseaseMLInterpretation.heart_disease_app.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
    healthCheckPath: /
    autoDeploy: true 